Avoid cargo 1.43–1.45 in GitHub Actions
These versions are incompatible with some recent GitHub change

    error: failed to get `serde` as a dependency of package `semver v1.0.12 (/home/runner/work/semver/semver)`

    Caused by:
      failed to load source for dependency `serde`

    Caused by:
      Unable to update registry `https://github.com/rust-lang/crates.io-index`

    Caused by:
      failed to fetch `https://github.com/rust-lang/crates.io-index`

    Caused by:
      error reading from the zlib stream; class=Zlib (5)